# Generated by Django 4.0.3 on 2022-07-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(null=True)),
                ('location', models.TextField(max_length=100)),
                ('profile_image', models.TextField(max_length=100)),
                ('social_github', models.TextField(max_length=100)),
                ('social_telegram', models.TextField(max_length=100)),
                ('social_instagram', models.TextField(max_length=100)),
                ('social_youtube', models.TextField(max_length=100)),
                ('social_website', models.TextField(max_length=100)),
                ('created', models.DateField(auto_now=True)),
            ],
        ),
    ]
