# Generated by Django 4.0.3 on 2022-07-05 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_github',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_instagram',
            field=models.TextField(default='instagram', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_telegram',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
