# Generated by Django 4.0.3 on 2022-07-05 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_bio_alter_profile_social_github_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='audio',
            field=models.FileField(null=True, upload_to='audios'),
        ),
        migrations.AddField(
            model_name='profile',
            name='file',
            field=models.FileField(null=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='profile',
            name='video',
            field=models.FileField(null=True, upload_to='videos'),
        ),
    ]
