# Generated by Django 4.0.3 on 2022-07-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_audio_profile_file_profile_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='audio',
            field=models.FileField(default='audios/default.mp3', upload_to='audios'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='file',
            field=models.FileField(default='files/default.docx', upload_to='files'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='video',
            field=models.FileField(default='videos/default.avi', upload_to='videos'),
        ),
    ]
