# Generated by Django 4.0.3 on 2022-07-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_audio_alter_profile_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='audio',
            field=models.FileField(upload_to='audios'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='file',
            field=models.FileField(default='files/default.xlsx', upload_to='files'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='video',
            field=models.FileField(upload_to='videos'),
        ),
    ]
