# Generated by Django 4.0.3 on 2022-07-05 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_project_alter_profile_file_alter_profile_location_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
