# Generated by Django 4.0.3 on 2022-07-05 08:00

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='file',
            field=models.FileField(blank=True, default='files/default.xlsx', upload_to='files', validators=[users.models.validate_file_extension]),
        ),
    ]
