# Generated by Django 4.0.3 on 2022-07-05 08:01

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_profile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='file',
            field=models.FileField(default='files/default.xlsx', upload_to='files', validators=[users.models.validate_file_extension]),
        ),
    ]
