# Generated by Django 4.0.3 on 2022-07-06 06:40

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_profile_audio_alter_profile_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files', validators=[users.models.validate_file_extension]),
        ),
    ]
